/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
  icon?: string;
  isExternal?: boolean;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteKeywords?: Array<string>;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  ctaText?: string;
  ctaUrl?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroBackground?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
  showServices?: boolean;
  showTestimonials?: boolean;
  googleAnalyticsId?: string;
  facebookPixelId?: string;
  twitterHandle?: string;
  footer?: {
    text?: string;
    copyrightText?: string;
    links?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
  };
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "archived";
  notes?: string;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  achievements?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  employmentType?:
    | "full-time"
    | "part-time"
    | "contract"
    | "freelance"
    | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "frontend" | "backend" | string | "ai-ml";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  percentage?: number;
  yearsOfExperience?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?:
    | "web-app"
    | "mobile-app"
    | "ai-ml"
    | "api-backend"
    | "devops"
    | "open-source"
    | "cli-tool"
    | "desktop-app"
    | "browser-extension"
    | "game"
    | "other";
  liveUrl?: string;
  githubUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  colorHeadline?: string;
  headline?: string;
  headlineStaticText?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  location?: string;
  availability?: "available" | "open" | "unavailable";
  socialLinks?: {
    github?: string;
    linkedin?: string;
    website?: string;
  };
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Navigation
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Contact
  | Education
  | Experience
  | Skill
  | Project
  | Slug
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: components/chat/ChatWrapper.tsx
// Variable: CHAT_PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{    _id,    _type,    _createdAt,    _updatedAt,    _rev,    firstName,    lastName,    headline,    shortBio,    email,    phone,    location,    availability,    socialLinks,    yearsOfExperience,    profileImage  }
export type CHAT_PROFILE_QUERY_RESULT =
  | {
      _id: "singleton-profile";
      _type: "contact";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "education";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "experience";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "navigation";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "profile";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      shortBio: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        website?: string;
      } | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | {
      _id: "singleton-profile";
      _type: "project";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "sanity.fileAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "siteSettings";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: "singleton-profile";
      _type: "skill";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | null;

// Source: components/dock/FloatingDock.tsx
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"] | order(order asc){  title,  href,  icon,  isExternal}
export type NAVIGATION_QUERY_RESULT = Array<{
  title: string | null;
  href: string | null;
  icon: string | null;
  isExternal: boolean | null;
}>;

// Source: components/sections/ContactSection.tsx
// Variable: PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{  email,  phone,  location,  socialLinks}
export type PROFILE_QUERY_RESULT =
  | {
      email: null;
      phone: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: null;
      phone: null;
      location: string | null;
      socialLinks: null;
    }
  | {
      email: string | null;
      phone: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: string | null;
      phone: string | null;
      location: string | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        website?: string;
      } | null;
    }
  | null;

// Source: components/sections/HeroSection.tsx
// Variable: HERO_QUERY
// Query: *[_id == "singleton-profile"][0]{		firstName,		lastName,		headline,		colorHeadline,		headlineStaticText,		headlineAnimatedWords,		headlineAnimationDuration,		shortBio,		email,		phone,		location,		availability,		socialLinks,		yearsOfExperience,		profileImage	}
export type HERO_QUERY_RESULT =
  | {
      firstName: null;
      lastName: null;
      headline: null;
      colorHeadline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      colorHeadline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      colorHeadline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      colorHeadline: null;
      headlineStaticText: null;
      headlineAnimatedWords: null;
      headlineAnimationDuration: null;
      shortBio: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      colorHeadline: string | null;
      headlineStaticText: string | null;
      headlineAnimatedWords: Array<string> | null;
      headlineAnimationDuration: number | null;
      shortBio: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      socialLinks: {
        github?: string;
        linkedin?: string;
        website?: string;
      } | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "singleton-profile"][0]{\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    firstName,\n    lastName,\n    headline,\n    shortBio,\n    email,\n    phone,\n    location,\n    availability,\n    socialLinks,\n    yearsOfExperience,\n    profileImage\n  }': CHAT_PROFILE_QUERY_RESULT;
    '*[_type == "navigation"] | order(order asc){\n  title,\n  href,\n  icon,\n  isExternal\n}': NAVIGATION_QUERY_RESULT;
    '*[_id == "singleton-profile"][0]{\n  email,\n  phone,\n  location,\n  socialLinks\n}': PROFILE_QUERY_RESULT;
    '*[_id == "singleton-profile"][0]{\n\t\tfirstName,\n\t\tlastName,\n\t\theadline,\n\t\tcolorHeadline,\n\t\theadlineStaticText,\n\t\theadlineAnimatedWords,\n\t\theadlineAnimationDuration,\n\t\tshortBio,\n\t\temail,\n\t\tphone,\n\t\tlocation,\n\t\tavailability,\n\t\tsocialLinks,\n\t\tyearsOfExperience,\n\t\tprofileImage\n\t}': HERO_QUERY_RESULT;
  }
}
